persistence true
log_dest stdout

listener 1883
allow_anonymous false

auth_plugin /mosquitto/go-auth.so
auth_opt_log_level info
auth_opt_backends http

auth_opt_http_host api-service
auth_opt_http_port 3001
auth_opt_http_getuser_uri /mqtt/auth
auth_opt_http_superuser_uri /mqtt/superuser
auth_opt_http_aclcheck_uri /mqtt/acl
auth_opt_http_method POST
auth_opt_http_params_mode json
auth_opt_http_response_mode status
