export const APPLIANCE_TYPES = [
  { value: '',                label: '— Select type —' },
  { value: 'fridge',          label: 'Refrigerator' },
  { value: 'washing_machine', label: 'Washing machine' },
  { value: 'dishwasher',      label: 'Dishwasher' },
  { value: 'dryer',           label: 'Dryer' },
  { value: 'ac',              label: 'Air conditioner' },
  { value: 'boiler',          label: 'Water heater / Boiler' },
  { value: 'ev_charger',      label: 'EV charger' },
  { value: 'heater',          label: 'Electric heater' },
  { value: 'lights',          label: 'Lights' },
  { value: 'air_purifier',    label: 'Air purifier' },
  { value: 'humidifier',      label: 'Humidifier' },
  { value: 'ventilation',     label: 'Ventilation / Heat recovery' },
  { value: 'tv',              label: 'TV / Entertainment' },
  { value: 'oven',            label: 'Oven / Microwave' },
  { value: 'sensor_temp',     label: 'Temperature sensor' },
  { value: 'sensor_humidity', label: 'Humidity sensor' },
  { value: 'sensor_co2',      label: 'CO2 / Air quality sensor' },
  { value: 'sensor_pressure', label: 'Pressure sensor' },
  { value: 'sensor_generic',  label: 'Sensor (generic)' },
  { value: 'other',           label: 'Other' },
]
